### ISSUE TITLE
localhost 3000 is not responding

### ISSUE THREAD

**Issue by gargabhay53** [philnash/sms-messages-app#11]
after running npm install and npm start application is not opening on localhost:3000.
http://localhost:3000/messages/new This end point is working but its not sending SMS.
Outbox, Inbox both are not working.

**Comment by philnash** [comment]
Hi @gargabhay53 

Did you copy the `.env.example` file to `.env` and fill it in with your Twilio account details?

Are there any error messages in the terminal or in the browser?

**Comment by gargabhay53** [comment]
yes I did and there is no error message or browser or terminal

**Comment by philnash** [comment]
Does the inbox/outbox just not load? And are you using this with a phone number that has a lot of messages? Because there is no pagination, and this app tries to load all the messages.

**Comment by gargabhay53** [comment]
no this is a new Twilio number we created and on the page load, a get API is called which is not responding at all.

**Comment by philnash** [comment]
Heh, there is also no error handling in the action. You might want to throw in some `catch` methods on the API calls and see what errors are being thrown.

**Comment by philnash** [comment]
Hey @gargabhay53, how are you getting on with this?
