### ISSUE TITLE
A few simple features are requested. I can contribute some $

### ISSUE THREAD

**Issue by 7thstorm** [philnash/sms-messages-app#8]
Hi there!
I would like to request 2 new features. If you can do this, I can contribute a few dollars to the development.

1. Need to be able to send and receive from multiple numbers...probably in a tabbed setting so I can view and respond to different numbers easily
2. Need the interface to automatically refresh when new message is received

Let me know if you have the time for this

**Comment by philnash** [comment]
You might be more interested in this more up to date project: https://github.com/jandusek/twilio-phone-client. It is more feature rich, plus is being worked on more actively. I don't believe it handles multiple numbers, but it does update with new messages and as a bonus, can make and receive phone calls too.

**Comment by 7thstorm** [comment]
Thank you!
